server:
  port: 8301
spring:
  application:
    name: ribbon-service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://xyy:123@192.168.0.36:8002/eureka/,http://xyy:123@192.168.0.36:8003/eureka/
service-url:
  user-service: http://user-service
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 0.1 #\u8BBE\u7F6ESleuth\u7684\u62BD\u6837\u6536\u96C6\u6982\u7387

