server:
  port: 9001
spring:
  application:
    name: config-client
  cloud:
    config:
      profile: xyy
      uri: http://localhost:8901
      name: bootstrap
eureka:
  client:
    service-url:
      defaultZone: http://xyy:123@192.168.0.36:8002/eureka/,http://xyy:123@192.168.0.36:8003/eureka/
management:
  endpoints:
    web:
      exposure:
        include: 'refresh'
